server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/usersdb
    username: tglav
    password: pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    logging:
      level:
        org:
          hibernate:
            SQL: debug
    show-sql: true
  main:
    web-application-type: servlet